"""
Token budget tracking and amortization analysis for the latent rollback bench.

Amortization model
------------------
Every injection-based condition (vec, matrix) has a fixed *setup cost*:
  - vec: one forward pass over the full context to extract the context vector.
  - matrix: one SVD pass over context hidden states.
  - model_summary F block: one generation pass to produce the summary (additional).

After setup, each query costs *per_query_tokens* (question + F block only),
vs. *baseline_per_query_tokens* (full context + question).

The break-even point N* satisfies:
    setup_tokens + N* × per_query_tokens  =  N* × baseline_per_query_tokens
    N* = setup_tokens / (baseline_per_query_tokens - per_query_tokens)

If N >= N*, the injection approach has spent fewer total tokens than baseline.

PassBudget records ONE pass (setup or query) for a given (condition, fblock)
combination.  Collect 5 passes (default) then call compute_amortization().

Import this module from any test file; no pytest infrastructure required.
"""

from __future__ import annotations

from dataclasses import dataclass


# ---------------------------------------------------------------------------
# Per-pass token record
# ---------------------------------------------------------------------------

@dataclass
class PassBudget:
    """Token costs for a single pass through the model."""

    pass_num: int           # 1-indexed pass number
    condition: str          # "baseline" | "vec" | "matrix"
    fblock: str             # "none" | "ner" | "bm25_single" | "bm25_double_seq"
                            # | "bm25_double_entity" | "model_summary"
    input_tokens: int       # tokens fed into the model for this pass
    output_tokens: int      # tokens generated by the model
    is_setup: bool          # True for context-extraction / summary-generation passes
    task_id: str = ""
    model_key: str = ""


# ---------------------------------------------------------------------------
# Amortization report
# ---------------------------------------------------------------------------

@dataclass
class AmortizationReport:
    """Amortization analysis across N query passes."""

    condition: str
    fblock: str
    task_id: str
    model_key: str

    # Costs
    setup_tokens: int               # tokens consumed in all setup passes
    per_query_tokens: int           # average input tokens per query pass
    baseline_per_query_tokens: int  # input tokens for full-context query

    # Amortization
    n_passes: int                   # number of query passes observed
    break_even_n: float             # N* where total cost equals baseline total
    is_amortized: bool              # True if n_passes >= break_even_n

    # Totals
    total_injection_cost: int       # setup + n_passes × per_query
    total_baseline_cost: int        # n_passes × baseline_per_query
    savings_pct: float              # 1 - total_injection / total_baseline


# ---------------------------------------------------------------------------
# Token approximation (no model required)
# ---------------------------------------------------------------------------

def approx_tokens(text: str) -> int:
    """
    Rough token count for a string without loading a tokenizer.

    Uses word count × 1.3 to account for subword splitting.
    Accurate to ±20% for typical English + code text.
    """
    return max(1, int(len(text.split()) * 1.3))


# ---------------------------------------------------------------------------
# Amortization computation
# ---------------------------------------------------------------------------

def compute_amortization(
    passes: list[PassBudget],
    baseline_per_query_tokens: int,
) -> AmortizationReport:
    """
    Compute the amortization report for a sequence of PassBudgets.

    Args:
        passes: All passes recorded for one (condition, fblock, task) run.
                Must contain at least one non-setup pass (query pass).
        baseline_per_query_tokens: Input tokens for the equivalent baseline
                                   (full-context) query.

    Returns:
        AmortizationReport with break-even analysis.

    Raises:
        ValueError: If no query passes are present, or passes is empty.
    """
    if not passes:
        raise ValueError("passes must be non-empty")

    query_passes = [p for p in passes if not p.is_setup]
    if not query_passes:
        raise ValueError("passes must contain at least one query pass (is_setup=False)")

    setup_tokens = sum(p.input_tokens for p in passes if p.is_setup)
    per_query = sum(p.input_tokens for p in query_passes) // len(query_passes)
    n = len(query_passes)

    savings_per_query = baseline_per_query_tokens - per_query
    if savings_per_query > 0:
        break_even = setup_tokens / savings_per_query
    elif savings_per_query == 0:
        break_even = float("inf")  # injection costs same per query — never cheaper
    else:
        break_even = float("inf")  # injection is MORE expensive per query — never amortized

    total_injection = setup_tokens + n * per_query
    total_baseline = n * baseline_per_query_tokens
    savings_pct = (
        1.0 - total_injection / total_baseline
        if total_baseline > 0 else 0.0
    )

    return AmortizationReport(
        condition=passes[0].condition,
        fblock=passes[0].fblock,
        task_id=passes[0].task_id,
        model_key=passes[0].model_key,
        setup_tokens=setup_tokens,
        per_query_tokens=per_query,
        baseline_per_query_tokens=baseline_per_query_tokens,
        n_passes=n,
        break_even_n=break_even,
        is_amortized=(n >= break_even and break_even != float("inf")),
        total_injection_cost=total_injection,
        total_baseline_cost=total_baseline,
        savings_pct=savings_pct,
    )


# ---------------------------------------------------------------------------
# Synthetic pass builder (for mocked / unit tests)
# ---------------------------------------------------------------------------

def build_mock_passes(
    condition: str,
    fblock: str,
    task_id: str,
    context_tokens: int,
    question_tokens: int,
    fblock_tokens: int,
    setup_tokens: int,
    n_query_passes: int = 5,
    output_tokens: int = 20,
    model_key: str = "mock",
) -> list[PassBudget]:
    """
    Build a list of PassBudgets without running a real model.

    The setup pass represents context-vector extraction (or summary generation).
    Each query pass represents question + F block tokens fed to the model.

    This is used by test_bench_metrics.py to test amortization math independently
    of any model infrastructure.
    """
    passes: list[PassBudget] = []

    # Setup pass: extract context (full context tokens consumed once)
    passes.append(PassBudget(
        pass_num=0,
        condition=condition,
        fblock=fblock,
        input_tokens=setup_tokens,
        output_tokens=0,
        is_setup=True,
        task_id=task_id,
        model_key=model_key,
    ))

    # Query passes: question + F block only
    per_query = question_tokens + fblock_tokens
    for i in range(n_query_passes):
        passes.append(PassBudget(
            pass_num=i + 1,
            condition=condition,
            fblock=fblock,
            input_tokens=per_query,
            output_tokens=output_tokens,
            is_setup=False,
            task_id=task_id,
            model_key=model_key,
        ))

    return passes
